index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellido}
    controller: App\Controller\HomeController::animales
    defaults: {nombre: 'Ingresa tu nombre', apellido: 'Ingresa el apellido'}
    methods: [POST, GET]
    requirements:
        nombre: '[a-zA-Z ]+'
        apellido: '[a-zA-Z ]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir